site_name: Neurograph
nav:
  - Getting Started: index.md
  - Data Extraction: 
    - Feature Extraction: data-extraction/feature-extraction.md 
    - Graph Markup Language: data-extraction/graph-markup-language.md
    - Language Data: data-extraction/language-data.md
    - Regular Expressions: data-extraction/regular-expressions.md
  - Data Structures:
    - Adjacency List: data-structures/adjacency-list.md
    - Adjacency Matrix: data-structures/adjacency-matrix.md
    - Node: data-structures/node.md
  - Graph Algorithms:
    - Centrality: graph-algorithms/centrality.md
    - Community Detection: graph-algorithms/community-detection.md
    - Pathfinding: graph-algorithms/pathfinding.md
    - Searching: graph-algorithms/searching.md
    - Utilities: graph-algorithms/utilities.md

theme:
  name: material
  palette:

   # Palette toggle for light mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
