site_name: Neurograph
nav:
  - Getting Started: index.md
  - Core Library Reference: core-library/core-library.md
  - Python Library: index.md
  - Suppport: index.md
  - Contribute: index.md
  - Releases: releases/releases.md

theme:
  name: material
  palette:

   # Palette toggle for light mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
