name: Diffusion CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Source
      working-directory: src/
      run: make

  built-core-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Test Harness
      working-directory: tests/
      run: make

  # unit tests for C code base
  core-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      working-directory: target/
      run: ./unit_test

  # run linter
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Action
      uses: wearerequired/lint-action@v2.3.0

