name: Diffusion CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Source
      working-directory: src/
      run: make

    - name: Build Test Harness
      working-directory: tests/
      run: make

  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      working-directory: target/
      run: ./unit_test

  clang-linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,c'
        clangFormatVersion: 14
        style: chromium
