name: Diffusion CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  # build source for unit tests
  build-core:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
    - name: Build and Test Graph Package
      working-directory: src/graph/
      run: |
        make
        ./target/test_graph
        make clean
       
  # unit tests for python code base
  build-dgraph:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
    - name: Test Graph Construct
      working-directory: dgraph/tests/
      run: python -m unittest -v test_graph
